open module FactionsUUID {
    requires static adventure.platform.bukkit;
    requires static api;
    requires static authlib;
    requires static brigadier;
    requires static com.google.common;
    requires static com.google.gson;
    requires static commodore;
    requires static denizen;
    requires static depenizen;
    requires static citizens.main;
    requires static dynmap;
    requires static EssentialsX;
    requires static Graves;
    requires java.logging;
    requires static MagicAPI;
    requires static Modern.LWC;
    requires static net.kyori.adventure;
    requires static net.kyori.adventure.text.minimessage;
    requires static net.kyori.adventure.text.serializer.gson;
    requires static net.kyori.adventure.text.serializer.legacy;
    requires static net.kyori.examination.api;
    requires static adventure.platform.api;
    requires static org.apache.commons.lang3;
    requires org.bukkit;
    requires static org.jetbrains.annotations;
    requires static org.jspecify;
    requires static org.spongepowered.configurate;
    requires static org.spongepowered.configurate.hocon;
    requires static paperlib;
    requires static placeholderapi;
    requires static PlayerVaultsX;
    requires static sentinel;
    requires static typesafe.config;
    requires static VaultAPI;
    requires static worldedit.bukkit;
    requires static worldedit.core;
    requires static worldguard.bukkit;
    requires static worldguard.core;
    requires static MVdWPlaceholderAPI;
}