name: "build"

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:

concurrency:
  cancel-in-progress: true
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"

env:
  RUNTIME_VERSION: 25

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    runs-on: ["ubuntu-latest"]
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v7"
      - name: "setup java ${{ env.RUNTIME_VERSION }}"
        uses: "actions/setup-java@v5"
        with:
          distribution: "corretto"
          java-version: "${{ env.RUNTIME_VERSION }}"
      - name: "setup gradle"
        uses: "gradle/actions/setup-gradle@v6"
      - name: "run gradle build"
        run: "./gradlew build"
