name: FactionsUUID
version: ${version}
main: dev.kitteh.factions.plugin.FactionsPluginPaper
authors: [Matt Baxter, Olof Larsson, Brett Flannigan, Trent Hensler, various other contributors over more than a dozen years]
api-version: '${apiversion}'
website: https://www.spigotmc.org/resources/factionsuuid.1035/

dependencies:
  server:
    LuckPerms:
      load: AFTER
      required: false
      join-classpath: true
    WorldGuard:
      load: AFTER
      required: false
      join-classpath: true
    Essentials:
      required: false
      join-classpath: true
    Depenizen:
      required: false
      join-classpath: true
    Duels:
      required: false
      join-classpath: true
    dynmap:
      required: false
      join-classpath: true
    Magic:
      required: false
      join-classpath: true
    PlaceholderAPI:
      required: false
      join-classpath: true
    Sentinel:
      required: false
      join-classpath: true
    Vault:
      required: false
      join-classpath: true
    YardWatch:
      required: false
      join-classpath: true

permissions:
  factions.kit.admin:
    description: All faction permissions.
    children:
      factions.kit.mod: true
      factions.autosave: true
      factions.reload: true
      factions.save: true
      factions.modifypower: true
      factions.ahome: true
      factions.setmaxvaults: true
      factions.updates: true
      factions.debug: true
  factions.*:
    description: This is just an alias for factions.kit.admin
    children:
      factions.kit.admin: true
  factions.kit.mod:
    description: All faction permissions but configuration and persistence.
    children:
      factions.kit.halfmod: true
      factions.disband.any: true
      factions.grace.set: true
      factions.setpeaceful: true
      factions.setpermanent: true
      factions.setpermanentpower: true
      factions.powerboost: true
      factions.money.*: true
  factions.kit.halfmod:
    description: Zones, bypassing, kicking, and chatspy
    children:
      factions.kit.fullplayer: true
      factions.managesafezone: true
      factions.managewarzone: true
      factions.bypass: true
      factions.force.role: true
      factions.kick.any: true
      factions.chatspy: true
      factions.show.bypassexempt: true
      factions.tnt.modify: true
  factions.kit.fullplayer:
    default: true
    description: Can also create new factions and use title colors.
    children:
      factions.kit.halfplayer: true
      factions.create: true
      factions.title.color: true
  factions.kit.halfplayer:
    description: Can do all but create factions.
    children:
      factions.admin: true
      factions.autoclaim: true
      factions.chat: true
      factions.claim: true
      factions.claim.line: true
      factions.claim.radius: true
      factions.confirm: true
      factions.coords: true
      factions.deinvite: true
      factions.description: true
      factions.disband: true
      factions.dtr: true
      factions.grace.view: true
      factions.help: true
      factions.home: true
      factions.invite: true
      factions.join: true
      factions.kick: true
      factions.leave: true
      factions.link: true
      factions.list: true
      factions.map: true
      factions.map.auto: true
      factions.money.kit.standard: true
      factions.noboom: true
      factions.open: true
      factions.power: true
      factions.power.any: true
      factions.promote: true
      factions.relation: true
      factions.sethome: true
      factions.delhome: true
      factions.shield: true
      factions.show: true
      factions.stuck: true
      factions.tag: true
      factions.title: true
      factions.unclaim: true
      factions.unclaimall: true
      factions.scoreboard: true
      factions.showinvites: true
      factions.seechunk: true
      factions.monitorlogins: true
      factions.top: true
      factions.vault: true
      factions.mapheight: true
      factions.ban: true
      factions.fly: true
      factions.near: true
      factions.permissions: true
      factions.upgrades: true
  factions.admin:
    description: hand over your admin rights
  factions.announce:
    description: announce things to the peasants
  factions.autoclaim:
    description: auto-claim land as you walk around
  factions.bypass:
    description: enable admin bypass mode
  factions.chat:
    description: change chat mode
  factions.chatspy:
    description: enable admin chat spy mode
  factions.claim:
    description: claim land where you are standing
  factions.claim.radius:
    description: claim land in a large radius
  factions.confirm:
    description: confirm a big change
  factions.create:
    description: create a new faction
  factions.deinvite:
    description: remove a pending invitation
  factions.description:
    description: change the faction description
  factions.disband:
    description: disband a faction
  factions.disband.any:
    description: disband another faction
  factions.grace.view:
    description: view grace status
  factions.grace.set:
    description: set grace
  factions.help:
    description: display a help page
  factions.home:
    description: teleport to the faction home
  factions.invite:
    description: invite a player to your faction
  factions.join:
    description: join a faction
  factions.kick:
    description: kick a player from the faction
  factions.kick.any:
    description: kick anyone from any faction
  factions.leave:
    description: leave your faction
  factions.list:
    description: see a list of the factions
  factions.link:
    description: see or set the faction's link
  factions.autosave:
    description: control autosaving
  factions.managesafezone:
    description: claim land as a safe zone and build/destroy within safe zones
  factions.managewarzone:
    description: claim land as a war zone and build/destroy within war zones
  factions.map:
    description: show the territory map
  factions.map.auto:
    description: set optional auto update for map
  factions.money.balance:
    description: show your factions current money balance
  factions.money.balance.any:
    description: show money balance for factions other than your own
  factions.money.deposit:
    description: deposit money into a faction bank
  factions.money.withdraw:
    description: withdraw money from your faction bank
  factions.money.withdraw.any:
    description: withdraw money from your factions other than your own
  factions.money.f2f:
    description: transfer money from faction to faction
  factions.money.f2p:
    description: transfer money from faction to player
  factions.money.kit.standard:
    children:
      factions.money.balance: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.withdraw: true
      factions.money.f2f: true
      factions.money.f2p: true
  factions.money.*:
    children:
      factions.money.kit.standard: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.withdraw: true
      factions.money.withdraw.any: true
      factions.money.f2f: true
      factions.money.f2p: true
  factions.noboom:
    description: toggle explosions (peaceful factions only)
  factions.open:
    description: switch if invitation is required to join
  factions.promote:
    description: promote members
  factions.setpeaceful:
    description: designate a faction as peaceful
  factions.setpermanent:
    description: designate a faction as permanent
  factions.setpermanentpower:
    description: set permanent power for a faction
  factions.stuck:
    description: teleports player outside a faction
  factions.power:
    description: show player power info
  factions.power.any:
    description: view an other players power level
  factions.powerboost:
    description: apply permanent power bonus/penalty to specified player or faction
  factions.relation:
    description: set relation wish to another faction
  factions.reload:
    description: reload data file(s) from disk
  factions.save:
    description: save all data to disk
  factions.sethome:
    description: set the faction home
  factions.delhome:
    description: unset the faction home
  factions.shield:
    description: use the shield feature
  factions.show:
    description: show faction information
  factions.show.bypassexempt:
    description: show exempt faction information
  factions.tag:
    description: change the faction tag
  factions.title:
    description: set or remove a players title
  factions.title.color:
    description: set yours or other player's titles to be colored.
  factions.unclaim:
    description: unclaim the land where you are standing
  factions.unclaimall:
    description: unclaim all of your factions land
  factions.scoreboard:
    description: ability to toggle scoreboards
  factions.showinvites:
    description: show pending invites to your faction
  factions.seechunk:
    description: see the chunk you stand in
  factions.setwarp:
    description: set a warp for your faction
  factions.warp:
    description: access your faction warps
  factions.dtr:
    description: view your faction's DTR
  factions.modifydtr:
    description: modify other factions' DTR
  factions.modifypower:
    description: modify other player's power
  factions.monitorlogins:
    description: monitor join and leaves of faction members
  factions.top:
    description: sort factions
  factions.dontlosepoweroffline:
    description: Don't lose power for being offline.
  factions.ahome:
    description: Ability to send players to their faction home.
  factions.autoleavebypass:
    description: Bypass autoleave.
  factions.vault:
    description: Access faction vault.
  factions.setmaxvault:
    description: Set a faction's max vaults.
  factions.mapheight:
    description: Set your /f map height.
  factions.ban:
    description: Ban players from Factions
  factions.fly:
    description: Allow use of /f fly
  factions.fly.auto:
    description: Allow use of /f fly auto
  factions.near:
    description: Allow use of /f near to show nearby faction members
  factions.updates:
    description: Be informed of available updates to the plugin
  factions.permissions:
    description: Use /f perms
  factions.debug:
    description: Use /f debug
  factions.tnt.info:
    description: Get TNT information
  factions.tnt.deposit:
    description: Deposit to TNT bank
  factions.tnt.withdraw:
    description: Withdraw from TNT bank
  factions.tnt.fill:
    description: Use TNT fill command
  factions.tnt.siphon:
    description: Use TNT siphon command
  factions.tnt.modify:
    description: Modify a faction's TNT bank
  factions.coords:
    description: Send coordinates to your teammates
  factions.listclaims:
    description: List claims
  factions.listclaims.other:
    description: List claims of other factions
  factions.upgrades:
    description: Show faction upgrades
  factions.force.role:
    description: Modify roles anywhere
  factions.force.join:
    description: Force a player to join a faction
